In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./data/alunos_02.jpg')

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# Load cascade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [13]:
image = img.copy()

# step - 1: convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# step - 2: apply grayscale image to cascade classifier 
face_rect = haar.detectMultiScale(gray, 1.2, 5)
# step - 3: draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image, (x,y), (x + w, y + h), (0,255,0), 2)


cv2.imshow('detected faces', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
print(face_rect)

[[ 536  241   59   59]
 [ 420  258   63   63]
 [ 626  259   58   58]
 [ 883  238   74   74]
 [ 724  294   55   55]
 [1075  279   75   75]
 [ 800  306   53   53]
 [ 248  330   59   59]]
