In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./data/alunos_02.jpg')

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# Load cascade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [11]:
image = img.copy()

# step - 1: convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# step - 2: apply grayscale image to cascade classifier 
face_rect = haar.detectMultiScale(gray, 1.2, 5)
# step - 3: draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image, (x,y), (x + w, y + h), (0,255,0), 2)


cv2.imshow('detected faces', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(face_rect)

[[ 535  240   59   59]
 [ 626  259   58   58]
 [ 886  240   69   69]
 [ 421  257   62   62]
 [1075  279   74   74]
 [ 632  205  303  303]
 [ 598   67   26   26]
 [ 726  295   54   54]
 [ 801  305   54   54]
 [1108  197   57   57]
 [ 806  518   58   58]
 [ 249  330   57   57]
 [ 925  683   58   58]
 [1020  336  110  110]]
